name: CI

on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Check out git repository
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Install dependencies
      run: npm ci
    - name: Run Lint
      run: npm run lint
    - name: Run Tests
      run: npm run test -- --coverage
